name: 功能開發
description: 新功能開發
title: "[Feature] 標題"
labels: ["type: feat:(feature)"]
body:
- type: textarea
  attributes:
    label: 需求
    description: 描述開發需求
  validations:
    required: true
- type: input
  attributes:
    label: 預計完成時間
    description: 格式 YYYY-MM-DD HH:MM
  validations:
    required: true
- type: textarea
  attributes:
    label: 其他補充
    description: |
      任何連結、截圖或影片等補充訊息。
  validations:
    required: false